### ISSUE TITLE
Found input variables with inconsistent numbers of samples: [497, 745]

### ISSUE THREAD

**Issue by dondonprad** [Rohit-Kundu/COVID-Detection-Gompertz-Function-Ensemble#1]
I have to try running main.py but there is an issue, show like on the title 
Thank you 
- python 3.6.2 
- using all requirements.txt package

**Comment by Rohit-Kundu** [comment]
The number of samples you have for different probability distributions is different. For the SARS-COV-2 dataset, there should be 745 test samples (which is correct in all the CSV files provided). Check which probability distribution is giving the wrong shape of 497.

Check function `getfile` in `utils_ensemble.py`. It takes the labels from the Data folder. So check whether you have the correct data distribution downloaded in your folder. Or you can hard-code it yourself for your own data instead of parsing from the folders.
